export const STORAGE_KEYS = {
  ONBOARDED: 'onboarded',
  USER_NAME: 'userName',
  GENDER: 'gender',
  WEIGHT: 'weight',
  HEIGHT: 'height',
  ACTIVITY: 'activity',
  DAILY_GOAL: 'dailyGoal',
  POINTS: 'points',
  UNLOCKED_BOTTLES: 'unlockedBottles',
  SELECTED_BOTTLE: 'selectedBottle',
  DATE: 'date',
  WATER: 'water',
  PREV_DAY_WATER: 'prevDayWater',
  STREAK: 'streak',
  TOTAL_DAYS: 'totalDays',
  BEST_DAY: 'bestDay',
  WEEKLY_DATA: 'weeklyData',
  COMPLETED_TASKS: 'completedTasks',
  DRINK_COUNT: 'drinkCount',
} as const;
